### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by federicohoerth** [mihe/node-hot#1]
Hi, how are you?
This module was very useful for me, couldn't figure it out how to reload a babel-compiled (through babel-register) React APP without triggering webpack build twice (the first because of `webpack-dev-middleware` and the second because of `babel-watch`).
I've tried several ways and mainly I was getting frustrated.
Until I tried `node-hot`.
Simple code example:
```
  require('node-hot');

  app.use('*', (req, res) => {
    const serverApp = require('./src/server').default;
    res.send(ReactDOMServer.renderToString(React.createElement(serverApp)));
  })
```
Now I simply run `node server.js` and in every request I get the app reloaded.
It would very useful if you update the `README.md` including this feature.

Regards.

**Comment by mihe** [comment]
Apologies for the much too late response. I only just now realized I hadn't been set to watch this repo.

I'm glad you got some use out of `node-hot`. Your trick is pretty clever, but I feel it's a bit too domain specific to mention in the `README`.
